name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        stale-issue-message: "This issue has been automatically closed because no recent activity has been identified."
        stale-pr-message: "This pull-request has been automatically closed because no recent activity has been identified."
        stale-issue-label: "NoActivity"
        stale-pr-label: "NoActivity"
